# Generated by Django 3.0.8 on 2020-10-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200722_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='surname',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
