# Generated by Django 3.0.8 on 2020-10-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_supplier_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='surname',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
