# Generated by Django 3.0.8 on 2020-10-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_buyer_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='phone',
            field=models.PositiveIntegerField(max_length=8, null=True),
        ),
    ]
