# Generated by Django 3.0.8 on 2020-10-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_buyer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.IntegerField(max_length=8, null=True),
        ),
    ]
