# Generated by Django 3.0.8 on 2020-10-11 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_buyer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='email',
        ),
    ]
