# Generated by Django 3.0.8 on 2020-10-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_buyer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='balances',
            field=models.PositiveIntegerField(max_length=7, null=True),
        ),
    ]
