# Generated by Django 3.0.8 on 2020-10-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_buyer_balances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='balances',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
