# Generated by Django 3.0.8 on 2020-10-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20201011_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='credit',
            field=models.PositiveIntegerField(max_length=7, null=True),
        ),
    ]
