# Generated by Django 3.0.8 on 2020-10-12 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_buyer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='user',
        ),
    ]
