# Generated by Django 3.0.8 on 2020-10-12 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='user',
        ),
    ]
