# Generated by Django 3.0.8 on 2020-10-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20201012_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='phoneSupplier',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
