# Generated by Django 3.0.8 on 2020-10-13 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20201012_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sortno',
            new_name='quantity',
        ),
    ]
