# Generated by Django 3.0.8 on 2020-10-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20201012_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='drop',
        ),
        migrations.DeleteModel(
            name='Drop',
        ),
    ]
