# Generated by Django 3.0.8 on 2020-10-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20201012_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cancelar', 'Cancelar'), ('Aprobado', 'Aprobado'), ('Procesando', 'Procesando'), ('Completado', 'Compleatado'), ('Aumentar', 'Aumentar')], max_length=10),
        ),
    ]
