# Generated by Django 3.0.8 on 2020-10-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_auto_20201013_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='dpi',
            field=models.CharField(default=2, max_length=24),
            preserve_default=False,
        ),
    ]
