# Generated by Django 3.0.8 on 2020-10-14 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_buyer_dpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adrres',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Addresses'),
            preserve_default=False,
        ),
    ]
