# Generated by Django 3.0.8 on 2020-10-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_product_precion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Precion',
            new_name='price',
        ),
    ]
