# Generated by Django 3.0.8 on 2020-10-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_order_cant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cant',
            new_name='quantityOrder',
        ),
    ]
