# Generated by Django 3.0.8 on 2020-10-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_auto_20201015_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantityOrder',
        ),
    ]
