# Generated by Django 3.0.8 on 2020-10-15 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_remove_order_quantityorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adrres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Addresses'),
        ),
    ]
