# Generated by Django 3.0.8 on 2020-10-15 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_auto_20201015_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adrres',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Addresses'),
            preserve_default=False,
        ),
    ]
